FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3.7-buster-build

WORKDIR /usr/app
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY src ./src
COPY balena-run.sh ./

RUN chmod +x balena-run.sh

CMD ./balena-run.sh